# Generated by Django 3.2 on 2021-06-05 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import khazen.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=128, verbose_name='file name')),
                ('file', models.FileField(upload_to=khazen.utils.gen_filename, verbose_name='file')),
                ('ext', models.CharField(blank=True, help_text='file mime-type', max_length=128, verbose_name='ext')),
                ('size', models.IntegerField(default=0, help_text='size of file in Megabyte', verbose_name='size')),
                ('type', models.IntegerField(choices=[(1, 'Image'), (2, 'Document'), (3, 'Compressed'), (4, 'Audio'), (5, 'Video'), (6, 'Other')], default=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('-uuid',),
            },
        ),
    ]
