# Generated by Django 3.0.5 on 2021-04-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khazen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-uuid',), 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
