# Generated by Django 3.2 on 2021-06-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(blank=True, help_text='Admin set the storage limit (MB)', null=True, verbose_name='storage')),
                ('storage_limit', models.IntegerField(help_text='size of user storage', verbose_name='storage_limit')),
                ('storage_current', models.IntegerField(default=0, help_text='size of user storage', verbose_name='storage_current')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
